// Test data only: about sixty made up groups with the kinds of gaps real data has. Never shipped to
// visitors (nothing in the site imports this file).
//
// Three kinds of record, like the real list:
//   thin   City records made by script: a name, a kind, a place, templated tags. No schedule, cost,
//          commitment, newcomer rating or access.
//   mixed  basic research (tier 1): a summary and tags, some of cost, days or a rating, never all.
//   deep   a deep research pass (tier 2): most fields filled in.
//
// The groups are built to give every fixture person something to find, and to give each rule
// something to catch: a court ordered yes, a sourced hour form, 18 plus groups, paid groups,
// support groups, a members only club, faith communities, student only groups, and candidates for
// each of the four kinds of stretch.

import { normalizeGroup } from '../lib/normalize';
import type { Group } from '../lib/types';
import { NEIGHBORHOOD_CENTERS } from './centroids';

type Raw = Record<string, unknown>;

function at(hood: string, dLat = 0, dLng = 0): { lat: number; lng: number } {
  const c = NEIGHBORHOOD_CENTERS[hood];
  if (!c) throw new Error(`unknown neighborhood ${hood}`);
  return { lat: Math.round((c[0] + dLat) * 1e4) / 1e4, lng: Math.round((c[1] + dLng) * 1e4) / 1e4 };
}

/** A meeting place with exact coordinates. */
function place(hood: string, label = 'Meeting place', dLat = 0, dLng = 0): Raw {
  return { label, neighborhood: hood, in_city: true, ...at(hood, dLat, dLng) };
}

/** A meeting place with only a neighborhood (no coordinates). */
function hoodOnly(hood: string): Raw {
  return { label: 'Meeting place', neighborhood: hood, in_city: true };
}

/** A place known only by its ZIP, like many City records. */
function zipOnly(zip: string): Raw {
  return { label: 'Meeting place', zip, in_city: true };
}

function g(over: Raw): Group {
  const base: Raw = {
    summary: 'A made up group for tests.',
    kind: 'club',
    audience: { open_to: 'public' },
    status: 'active',
    last_sign_of_life: '2026-09',
    research_tier: 1,
    confidence: 'medium',
  };
  const merged: Raw = { ...base, ...over, audience: { ...(base.audience as Raw), ...((over.audience as Raw) ?? {}) } };
  return normalizeGroup(merged);
}

/** A thin City record: no schedule, cost, commitment, rating or access. */
function thin(id: string, name: string, kind: string, categories: string[], interests: string[], loc: Raw, over: Raw = {}): Group {
  return g({
    id,
    name,
    kind,
    categories,
    interests,
    motives: ['values', 'social'],
    formats: ['conversation', 'lead_organize'],
    roles: ['organize', 'figure_out'],
    crowd: ['neighbors'],
    locations: [loc],
    last_sign_of_life: '2026-10',
    summary: `${name} is on the City's list of registered groups. It is a made up record for tests.`,
    ...over,
  });
}

const free = { level: 'free' };
const low = { level: 'low' };
const paid = { level: 'paid' };

export function testGroups(): Group[] {
  return [
    // ------------------------------------------------------------ thin City records (16)
    thin('mayfair-civic-association', 'Mayfair Civic Association', 'civic', ['neighborhood-civic'], ['civic_association'], hoodOnly('mayfair'), { audience: { open_to: 'residents' } }),
    thin('olney-community-council', 'Olney Community Council', 'civic', ['neighborhood-civic'], ['civic_association', 'community_development'], zipOnly('19141'), { audience: { open_to: 'residents' } }),
    thin('friends-of-cobbs-creek-park', 'Friends of Cobbs Creek Park', 'friends_group', ['nature-environment'], ['friends_of_park', 'park_cleanup'], place('cobbs_creek'), {
      motives: ['values'],
      formats: ['side_by_side'],
      roles: ['hands_on'],
    }),
    thin('friends-of-pennypack-trail', 'Friends of Pennypack Trail', 'friends_group', ['nature-environment', 'outdoors-adventure'], ['friends_of_park', 'hiking'], zipOnly('19136')),
    thin('kingsessing-rec-center-council', 'Kingsessing Rec Center Council', 'program', ['neighborhood-civic'], ['rec_center_council'], place('kingsessing')),
    thin('oxford-circle-town-watch', 'Oxford Circle Town Watch', 'civic', ['neighborhood-civic'], ['town_watch'], hoodOnly('oxford_circle')),
    thin('fishtown-library-friends', 'Fishtown Library Friends', 'friends_group', ['books-writing'], ['library_programs'], place('fishtown', 'Branch library')),
    thin('point-breeze-community-garden', 'Point Breeze Community Garden', 'garden', ['gardening-greening'], ['community_garden'], place('point_breeze'), {
      motives: ['values', 'protective'],
      formats: ['side_by_side'],
      roles: ['hands_on'],
    }),
    thin('tacony-community-garden', 'Tacony Community Garden', 'garden', ['gardening-greening'], ['community_garden'], hoodOnly('tacony'), { formats: ['side_by_side'], roles: ['hands_on'] }),
    thin('south-philly-senior-center', 'South Philly Senior Center', 'program', ['seniors-intergenerational'], ['senior_centers'], place('east_passyunk'), {
      audience: { open_to: 'public', min_age: 55 },
      crowd: ['seniors'],
    }),
    thin('hunting-park-youth-league', 'Hunting Park Youth League', 'program', ['sports-teams', 'kids-youth-mentoring'], ['youth_coaching'], place('hunting_park'), {
      audience: { open_to: 'public', min_age: 5, max_age: 14 },
      crowd: ['kids'],
      formats: ['team_play'],
      roles: ['hands_on', 'help_teach'],
    }),
    thin('east-passyunk-block-captains', 'East Passyunk Block Captains', 'civic', ['neighborhood-civic'], ['block_captain'], place('east_passyunk', 'Meeting place', 0.002, 0.001)),
    thin('cobbs-creek-rec-pottery', 'Cobbs Creek Rec Center Pottery', 'program', ['arts-crafts'], ['pottery_ceramics'], place('cobbs_creek', 'Rec center', 0.003, 0.002), {
      formats: ['learn_skill', 'side_by_side'],
      roles: ['create', 'hands_on'],
    }),
    thin('penn-hiking-club', 'Penn Hiking Club', 'student_org', ['outdoors-adventure'], ['hiking'], place('spruce_hill'), {
      audience: { open_to: 'students', school: 'penn' },
      crowd: ['students'],
      formats: ['side_by_side'],
      roles: ['hands_on'],
    }),
    thin('drexel-board-game-society', 'Drexel Board Game Society', 'student_org', ['games-puzzles'], ['board_games'], place('spruce_hill', 'Student center', 0.001, 0.001), {
      audience: { open_to: 'students', school: 'drexel' },
      crowd: ['students'],
      formats: ['conversation', 'team_play'],
      roles: ['figure_out'],
    }),
    thin('manayunk-neighbors-network', 'Manayunk Neighbors Network', 'civic', ['neighborhood-civic', 'social-meetups'], ['civic_association', 'newcomer_meetups'], place('manayunk'), {
      crowd: ['newcomers', 'neighbors'],
      motives: ['social', 'values'],
      formats: ['conversation'],
      roles: ['help_teach'],
    }),

    // ------------------------------------------------------------ mixed records, basic research (29)
    g({
      id: 'wissahickon-trail-crew',
      name: 'Wissahickon Trail Crew',
      kind: 'club',
      categories: ['nature-environment'],
      interests: ['trail_building'],
      motives: ['values', 'protective'],
      formats: ['side_by_side'],
      roles: ['hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 14 },
      schedule: { days: ['sat'], times: ['morning'], recurring: true },
      locations: [place('mount_airy_east', 'Trailhead')],
      cost: free,
      commitment: 'drop_in',
      group_size: 'medium',
      requirements: { kids_ok: true, service_hours_letter: 'yes' },
      first_step: { how: 'Come to a Saturday work day and ask for the crew lead', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'saturday-park-cleanups',
      name: 'Saturday Park Cleanups',
      kind: 'nonprofit',
      categories: ['nature-environment'],
      interests: ['park_cleanup'],
      motives: ['values', 'social'],
      formats: ['side_by_side', 'one_off_event'],
      roles: ['hands_on'],
      crowd: ['all_ages'],
      bridging: true,
      audience: { open_to: 'public', min_age: 10 },
      schedule: { days: ['sat'], times: ['morning'], recurring: true },
      locations: [place('kingsessing', 'Park entrance', 0.004, -0.002)],
      cost: free,
      commitment: 'drop_in',
      group_size: 'large',
      requirements: { kids_ok: true, court_ordered_ok: 'yes', service_hours_letter: 'yes' },
      first_step: { how: 'Show up at the park entrance and sign the sheet', drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'kensington-food-pantry',
      name: 'Kensington Food Pantry Volunteers',
      kind: 'nonprofit',
      categories: ['hunger-housing-basic-needs'],
      interests: ['food_pantry'],
      motives: ['values', 'social', 'career'],
      formats: ['behind_the_scenes', 'side_by_side'],
      roles: ['hands_on', 'organize'],
      crowd: ['neighbors'],
      audience: { open_to: 'public', min_age: 16 },
      schedule: { days: ['tue', 'thu', 'sat'], times: ['morning', 'afternoon'], recurring: true },
      locations: [place('fishtown', 'Pantry', 0.006, 0.004)],
      cost: free,
      commitment: 'weekly',
      group_size: 'medium',
      access: { wheelchair: 'yes', languages: ['en', 'es'] },
      requirements: { court_ordered_ok: 'yes', service_hours_letter: 'yes' },
      first_step: { how: 'Email the volunteer coordinator to pick a shift', sign_up_needed: true, newcomer_friendliness: 4 },
      research_tier: 2,
    }),
    g({
      id: 'fishtown-community-fridge',
      name: 'Fishtown Community Fridge',
      kind: 'network',
      categories: ['hunger-housing-basic-needs'],
      interests: ['community_fridge', 'mutual_aid'],
      motives: ['values'],
      formats: ['side_by_side', 'behind_the_scenes'],
      roles: ['hands_on'],
      crowd: ['neighbors'],
      audience: { open_to: 'public' },
      locations: [place('fishtown', 'The fridge', -0.003, 0.003)],
      cost: free,
      commitment: 'drop_in',
      requirements: { court_ordered_ok: 'yes', service_hours_letter: 'yes' },
      first_step: { how: 'Stock the fridge any time and take a photo for the group chat', drop_in: true },
    }),
    g({
      id: 'home-repair-volunteers',
      name: 'Neighborhood Home Repair Volunteers',
      kind: 'nonprofit',
      categories: ['hunger-housing-basic-needs'],
      interests: ['home_repair'],
      motives: ['values', 'career'],
      formats: ['side_by_side', 'learn_skill'],
      roles: ['hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['sat'], times: ['daytime'], recurring: true },
      locations: [place('point_breeze', 'Work sites vary', 0.005, 0.002)],
      cost: free,
      commitment: 'weekly',
      requirements: { court_ordered_ok: 'yes', background_check: true },
      first_step: { how: 'Fill in the volunteer form', sign_up_needed: true, newcomer_friendliness: 3 },
      research_tier: 2,
    }),
    g({
      id: 'shelter-dog-walkers',
      name: 'Shelter Dog Walkers',
      kind: 'program',
      categories: ['animals'],
      interests: ['shelter_volunteering'],
      motives: ['values', 'protective'],
      formats: ['side_by_side'],
      roles: ['hands_on', 'help_teach'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 16 },
      schedule: { days: ['sat', 'sun'], times: ['morning'], recurring: true },
      locations: [place('hunting_park', 'Animal shelter', 0.004, 0.003)],
      cost: free,
      commitment: 'weekly',
      group_size: 'medium',
      requirements: { service_hours_letter: 'yes' },
      first_step: { how: 'Sign up for an orientation, then pick walking shifts', sign_up_needed: true, newcomer_friendliness: 3 },
    }),
    g({
      id: 'adult-pickup-soccer',
      name: 'Adult Pickup Soccer',
      kind: 'club',
      categories: ['sports-teams'],
      interests: ['soccer'],
      motives: ['social', 'protective'],
      formats: ['team_play'],
      roles: ['hands_on'],
      crowd: ['young_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['sun'], times: ['morning'], recurring: true },
      locations: [place('rittenhouse', 'The fields', -0.004, -0.008)],
      cost: low,
      commitment: 'drop_in',
      group_size: 'large',
      first_step: { how: 'Show up at the fields and ask who needs a player', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'south-philly-kickball',
      name: 'South Philly Kickball League',
      kind: 'team',
      categories: ['sports-teams'],
      interests: ['kickball_rec_leagues'],
      motives: ['social'],
      formats: ['team_play'],
      roles: ['hands_on'],
      crowd: ['young_adults'],
      audience: { open_to: 'public', min_age: 21 },
      schedule: { days: ['wed'], times: ['evening'], recurring: true },
      locations: [place('east_passyunk', 'Field', -0.004, 0.002)],
      cost: paid,
      commitment: 'seasonal',
      group_size: 'large',
      first_step: { how: 'Join as a free agent and get placed on a team', sign_up_needed: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'learn-to-row-days',
      name: 'Learn to Row Days',
      kind: 'club',
      categories: ['water-rowing'],
      interests: ['rowing'],
      motives: ['enhancement', 'understanding'],
      formats: ['learn_skill', 'team_play'],
      roles: ['hands_on'],
      crowd: ['all_adults'],
      bridging: true,
      audience: { open_to: 'public', min_age: 16 },
      schedule: { days: ['sat'], times: ['morning'], recurring: false, season: 'summer' },
      locations: [{ label: 'Boathouse Row', in_city: true, lat: 39.9695, lng: -75.1856 }],
      cost: low,
      commitment: 'one_off',
      group_size: 'medium',
      first_step: { how: 'Book a beginner day online', sign_up_needed: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'chinatown-lion-dance',
      name: 'Chinatown Lion Dance Class',
      kind: 'club',
      categories: ['theater-dance-performance', 'culture-language-heritage-groups'],
      interests: ['cultural_dance', 'heritage_clubs'],
      motives: ['understanding', 'social', 'enhancement'],
      formats: ['learn_skill', 'perform_make_together'],
      roles: ['create', 'hands_on'],
      crowd: ['all_ages'],
      bridging: true,
      audience: { open_to: 'public' },
      schedule: { days: ['sat'], times: ['daytime'], recurring: true },
      locations: [place('chinatown', 'Dance hall')],
      cost: low,
      commitment: 'drop_in',
      group_size: 'medium',
      access: { languages: ['en', 'zh'] },
      first_step: { how: 'Watch a class, then join in', drop_in: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'mummers-open-rehearsal',
      name: 'Mummers String Band Open Rehearsal',
      kind: 'club',
      categories: ['philly-traditions', 'music'],
      interests: ['mummers_string_band', 'community_band'],
      motives: ['social', 'enhancement'],
      formats: ['perform_make_together'],
      roles: ['create'],
      crowd: ['all_ages'],
      bridging: true,
      audience: { open_to: 'public' },
      schedule: { days: ['wed'], times: ['evening'], recurring: true },
      locations: [place('east_passyunk', 'Clubhouse', 0.006, 0.0)],
      cost: free,
      commitment: 'drop_in',
      group_size: 'large',
      first_step: { how: 'Come to an open rehearsal and listen first', drop_in: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'spruce-hill-community-choir',
      name: 'Spruce Hill Community Choir',
      kind: 'club',
      categories: ['music'],
      interests: ['choir_singing'],
      motives: ['social', 'protective'],
      formats: ['perform_make_together'],
      roles: ['create'],
      crowd: ['all_adults'],
      audience: { open_to: 'public' },
      schedule: { days: ['tue'], times: ['evening'], recurring: true },
      locations: [place('spruce_hill', 'Church hall')],
      cost: low,
      commitment: 'weekly',
      group_size: 'medium',
      access: { wheelchair: 'yes' },
      first_step: { how: 'Come to the first rehearsal of a season', newcomer_friendliness: 4 },
    }),
    g({
      id: 'fishtown-improv-night',
      name: 'Fishtown Improv Night',
      kind: 'club',
      categories: ['theater-dance-performance'],
      interests: ['improv_comedy'],
      motives: ['enhancement', 'social'],
      formats: ['perform_make_together'],
      roles: ['create'],
      crowd: ['young_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['thu'], times: ['evening'], recurring: true },
      locations: [place('fishtown', 'Studio', 0.002, -0.003)],
      cost: paid,
      commitment: 'weekly',
      group_size: 'small',
      first_step: { how: 'Sign up for the beginner series', sign_up_needed: true, newcomer_friendliness: 3 },
    }),
    g({
      id: 'central-library-book-club',
      name: 'Central Library Book Club',
      kind: 'program',
      categories: ['books-writing'],
      interests: ['book_club'],
      motives: ['social', 'understanding'],
      formats: ['conversation'],
      roles: ['figure_out'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 16 },
      schedule: { days: ['tue'], times: ['evening'], recurring: true },
      locations: [place('rittenhouse', 'Library', 0.001, 0.002)],
      cost: free,
      commitment: 'monthly',
      group_size: 'small',
      access: { wheelchair: 'yes', languages: ['en'] },
      first_step: { how: 'Walk in and join the circle', drop_in: true, newcomer_friendliness: 4 },
      research_tier: 2,
    }),
    g({
      id: 'literacy-tutoring-network',
      name: 'Adult Literacy Tutoring Network',
      kind: 'nonprofit',
      categories: ['books-writing'],
      interests: ['literacy_tutoring'],
      motives: ['values', 'career'],
      formats: ['conversation', 'learn_skill'],
      roles: ['help_teach'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 16 },
      schedule: { days: ['mon', 'wed'], times: ['evening'], recurring: true },
      locations: [place('olney', 'Library branch')],
      cost: free,
      commitment: 'weekly',
      requirements: { service_hours_letter: 'yes', act153_clearances: true, background_check: true },
      first_step: { how: 'Attend a tutor training night', sign_up_needed: true, newcomer_friendliness: 3 },
      research_tier: 2,
    }),
    g({
      id: 'books-for-prisoners-packing',
      name: 'Books for Prisoners Packing Night',
      kind: 'network',
      categories: ['books-writing'],
      interests: ['prison_book_programs'],
      motives: ['values', 'social'],
      formats: ['behind_the_scenes', 'side_by_side'],
      roles: ['organize', 'hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'public' },
      schedule: { days: ['sun'], times: ['afternoon'], recurring: true },
      locations: [place('spruce_hill', 'Bookstore basement', 0.003, 0.002)],
      cost: free,
      commitment: 'drop_in',
      requirements: { court_ordered_ok: 'unknown' },
      first_step: { how: 'Come to a packing night, no sign up', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'west-philly-bike-coop',
      name: 'West Philly Bike Co-op',
      kind: 'nonprofit',
      categories: ['running-cycling-fitness'],
      interests: ['bike_repair'],
      motives: ['understanding', 'social'],
      formats: ['side_by_side', 'learn_skill'],
      roles: ['hands_on', 'help_teach'],
      crowd: ['all_ages'],
      audience: { open_to: 'public', min_age: 12 },
      schedule: { days: ['wed', 'sat'], times: ['evening', 'daytime'], recurring: true },
      locations: [place('cobbs_creek', 'Shop', -0.004, -0.003)],
      cost: low,
      commitment: 'drop_in',
      group_size: 'medium',
      access: { wheelchair: 'partial' },
      requirements: { kids_ok: true, service_hours_letter: 'yes' },
      first_step: { how: 'Drop in on a shop night and ask for a volunteer to show you around', drop_in: true, newcomer_friendliness: 4 },
      research_tier: 2,
    }),
    g({
      id: 'monthly-repair-cafe',
      name: 'Monthly Repair Cafe',
      kind: 'program',
      categories: ['making-tech'],
      interests: ['repair_cafe'],
      motives: ['values', 'understanding'],
      formats: ['side_by_side', 'one_off_event'],
      roles: ['hands_on', 'figure_out'],
      crowd: ['neighbors'],
      audience: { open_to: 'public' },
      schedule: { days: ['sat'], times: ['daytime'], recurring: true },
      locations: [place('mount_airy_east', 'Community hall', 0.002)],
      cost: free,
      commitment: 'monthly',
      first_step: { how: 'Bring something broken, or come to help', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'kensington-makerspace',
      name: 'Kensington Makerspace',
      kind: 'club',
      categories: ['making-tech'],
      interests: ['makerspace', 'woodworking'],
      motives: ['understanding', 'enhancement'],
      formats: ['learn_skill', 'side_by_side'],
      roles: ['create', 'hands_on'],
      crowd: ['young_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['tue', 'thu', 'sat'], times: ['evening'], recurring: true },
      locations: [place('fishtown', 'Shop', 0.008, 0.004)],
      cost: paid,
      commitment: 'weekly',
      access: { wheelchair: 'partial' },
      first_step: { how: 'Take the orientation tour on a Saturday', sign_up_needed: true, newcomer_friendliness: 3 },
    }),
    g({
      id: 'amateur-astronomers',
      name: 'Amateur Astronomers of Philadelphia',
      kind: 'club',
      categories: ['science-learning'],
      interests: ['astronomy'],
      motives: ['understanding'],
      formats: ['learn_skill', 'conversation'],
      roles: ['figure_out'],
      crowd: ['all_adults'],
      audience: { open_to: 'public' },
      schedule: { days: ['fri'], times: ['evening'], recurring: true },
      locations: [place('manayunk', 'Observatory', 0.01, 0.004)],
      cost: low,
      commitment: 'monthly',
      first_step: { how: 'Come to a public star night', drop_in: true, newcomer_friendliness: 3 },
    }),
    g({
      id: 'neighborhood-walking-tours',
      name: 'Neighborhood History Walking Tours',
      kind: 'program',
      categories: ['history-heritage-preservation'],
      interests: ['walking_tours'],
      motives: ['understanding', 'values'],
      formats: ['conversation', 'side_by_side'],
      roles: ['help_teach', 'figure_out'],
      crowd: ['all_ages'],
      bridging: true,
      audience: { open_to: 'public' },
      locations: [place('rittenhouse', 'Meeting corner', -0.002, 0.004)],
      commitment: 'seasonal',
      first_step: { newcomer_friendliness: 4 },
    }),
    g({
      id: 'esl-conversation-circle',
      name: 'ESL Conversation Circle',
      kind: 'program',
      categories: ['culture-language-heritage-groups'],
      interests: ['esl_conversation'],
      motives: ['social', 'understanding', 'values'],
      formats: ['conversation'],
      roles: ['help_teach'],
      crowd: ['newcomers', 'neighbors'],
      bridging: true,
      audience: { open_to: 'public', min_age: 16 },
      schedule: { days: ['wed'], times: ['evening'], recurring: true },
      locations: [place('olney', 'Library', 0.002, 0.002)],
      cost: free,
      commitment: 'weekly',
      group_size: 'small',
      access: { languages: ['en', 'es'], wheelchair: 'yes' },
      first_step: { how: 'Just come. No sign up, no test', drop_in: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'language-exchange-meetup',
      name: 'Language Exchange Meetup',
      kind: 'network',
      categories: ['culture-language-heritage-groups', 'social-meetups'],
      interests: ['language_exchange', 'conversation_circles'],
      motives: ['social', 'understanding'],
      formats: ['conversation'],
      roles: ['figure_out', 'help_teach'],
      crowd: ['young_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['thu'], times: ['evening'], recurring: true },
      locations: [place('rittenhouse', 'Cafe', 0.003, -0.002)],
      cost: free,
      commitment: 'weekly',
      access: { languages: ['en', 'es'] },
      first_step: { how: 'Show up and pick a language table', drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'st-agnes-community-meal',
      name: "St. Agnes Community Meal",
      kind: 'congregation',
      categories: ['faith-community', 'food-drink'],
      interests: ['community_meals', 'faith_service_projects'],
      motives: ['values', 'social'],
      formats: ['behind_the_scenes', 'side_by_side'],
      roles: ['hands_on', 'organize'],
      crowd: ['neighbors', 'all_ages'],
      bridging: true,
      audience: { open_to: 'public', faith: 'catholic' },
      schedule: { days: ['sun'], times: ['afternoon'], recurring: true },
      locations: [place('olney', 'Parish hall', -0.002, 0.001)],
      cost: free,
      commitment: 'weekly',
      access: { languages: ['en', 'es'] },
      requirements: { kids_ok: true, service_hours_letter: 'yes' },
      first_step: { how: 'Come to the hall by noon on Sunday', drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'masjid-food-drive',
      name: 'Masjid Neighbor Food Drive',
      kind: 'congregation',
      categories: ['faith-community', 'hunger-housing-basic-needs'],
      interests: ['faith_service_projects', 'food_pantry'],
      motives: ['values'],
      formats: ['behind_the_scenes'],
      roles: ['hands_on', 'organize'],
      crowd: ['neighbors'],
      audience: { open_to: 'public', faith: 'muslim' },
      schedule: { days: ['fri'], times: ['afternoon'], recurring: true },
      locations: [place('cobbs_creek', 'Masjid', 0.002, -0.004)],
      cost: free,
      commitment: 'monthly',
      first_step: { newcomer_friendliness: 4 },
    }),
    g({
      id: 'interfaith-service-day',
      name: 'Interfaith Service Day',
      kind: 'network',
      categories: ['faith-community'],
      interests: ['interfaith', 'faith_service_projects'],
      motives: ['values', 'social'],
      formats: ['side_by_side', 'one_off_event'],
      roles: ['hands_on'],
      crowd: ['all_ages'],
      bridging: true,
      audience: { open_to: 'public', faith: 'interfaith' },
      locations: [place('spruce_hill', 'Varies', -0.003, 0.004)],
      cost: free,
      commitment: 'one_off',
      first_step: { drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'center-city-newcomer-meetup',
      name: 'Center City Newcomer Meetup',
      kind: 'network',
      categories: ['social-meetups'],
      interests: ['newcomer_meetups', 'conversation_circles'],
      motives: ['social'],
      formats: ['conversation'],
      roles: ['help_teach'],
      crowd: ['newcomers', 'young_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['thu'], times: ['evening'], recurring: true },
      locations: [place('rittenhouse', 'Cafe', 0.002, 0.003)],
      cost: free,
      commitment: 'monthly',
      group_size: 'medium',
      first_step: { how: 'Come to the next gathering and wear a name tag', drop_in: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'young-adult-social-club',
      name: 'Young Adult Social Club',
      kind: 'club',
      categories: ['social-meetups'],
      interests: ['young_adult_social'],
      motives: ['social'],
      formats: ['conversation', 'team_play'],
      roles: ['help_teach'],
      crowd: ['young_adults'],
      audience: { open_to: 'public', min_age: 21, max_age: 39 },
      schedule: { days: ['fri'], times: ['evening'], recurring: true },
      locations: [place('fishtown', 'Bar', -0.002, -0.004)],
      cost: paid,
      commitment: 'weekly',
      first_step: { newcomer_friendliness: 3 },
    }),
    g({
      id: 'public-speaking-club',
      name: 'Friendly Public Speaking Club',
      kind: 'club',
      categories: ['careers-skills-professional'],
      interests: ['public_speaking'],
      motives: ['career', 'enhancement'],
      formats: ['learn_skill', 'lead_organize'],
      roles: ['lead', 'create'],
      crowd: ['professionals'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['mon'], times: ['evening'], recurring: true },
      locations: [place('rittenhouse', 'Office meeting room', 0.0, 0.006)],
      cost: low,
      commitment: 'weekly',
      group_size: 'small',
      first_step: { how: 'Visit as a guest, no speech required', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'neighborhood-cpr-classes',
      name: 'Neighborhood CPR and First Aid Classes',
      kind: 'program',
      categories: ['emergency-disaster'],
      interests: ['first_aid_cpr'],
      motives: ['understanding', 'career', 'values'],
      formats: ['learn_skill', 'one_off_event'],
      roles: ['hands_on', 'figure_out'],
      crowd: ['neighbors'],
      audience: { open_to: 'public' },
      locations: [place('overbrook', 'Rec center', 0.0, 0.002)],
      cost: low,
      commitment: 'one_off',
      requirements: { kids_ok: true },
      first_step: { how: 'Pick a class date online', sign_up_needed: true },
    }),

    // ------------------------------------------------------------ deep records, with a role or a new crowd (8)
    g({
      id: 'intergenerational-garden',
      name: 'Intergenerational Garden',
      kind: 'garden',
      categories: ['gardening-greening', 'seniors-intergenerational'],
      interests: ['community_garden', 'intergenerational'],
      motives: ['social', 'values', 'protective'],
      formats: ['side_by_side'],
      roles: ['hands_on', 'help_teach'],
      crowd: ['all_ages', 'seniors', 'families'],
      bridging: true,
      audience: { open_to: 'public' },
      schedule: { days: ['sat'], times: ['morning'], recurring: true },
      locations: [place('mount_airy_east', 'Garden', -0.003, 0.002)],
      cost: free,
      commitment: 'weekly',
      group_size: 'medium',
      access: { wheelchair: 'yes', languages: ['en'] },
      requirements: { kids_ok: true },
      first_step: { how: 'Come on a Saturday morning and pick a bed to weed', drop_in: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'friendly-visiting-program',
      name: 'Friendly Visiting Program',
      kind: 'nonprofit',
      categories: ['seniors-intergenerational'],
      interests: ['friendly_visiting'],
      motives: ['values', 'social'],
      formats: ['conversation', 'side_by_side'],
      roles: ['help_teach'],
      crowd: ['seniors'],
      audience: { open_to: 'public', min_age: 18 },
      locations: [place('east_passyunk', 'Office', 0.001, -0.002)],
      cost: free,
      commitment: 'ongoing_role',
      requirements: { background_check: true, service_hours_letter: 'yes' },
      first_step: { how: 'Apply and meet the coordinator', sign_up_needed: true, newcomer_friendliness: 3 },
      research_tier: 2,
    }),
    g({
      id: 'youth-mentoring-program',
      name: 'Youth Mentoring Program',
      kind: 'nonprofit',
      categories: ['kids-youth-mentoring'],
      interests: ['mentoring'],
      motives: ['values', 'enhancement'],
      formats: ['conversation', 'side_by_side'],
      roles: ['help_teach', 'lead'],
      crowd: ['kids', 'teens'],
      audience: { open_to: 'public', min_age: 21 },
      schedule: { days: ['tue', 'thu'], times: ['afternoon'], recurring: true },
      locations: [place('hunting_park', 'Program site')],
      cost: free,
      commitment: 'ongoing_role',
      requirements: { act153_clearances: true, background_check: true, service_hours_letter: 'yes' },
      first_step: { how: 'Attend an information session', sign_up_needed: true, newcomer_friendliness: 2 },
      research_tier: 2,
    }),
    g({
      id: 'parent-playgroup-spruce-hill',
      name: 'Spruce Hill Parent Playgroup',
      kind: 'club',
      categories: ['kids-youth-mentoring'],
      interests: ['parent_playgroups'],
      motives: ['social', 'protective'],
      formats: ['conversation', 'side_by_side'],
      roles: ['help_teach'],
      crowd: ['families'],
      audience: { open_to: 'parents', max_age: 99 },
      schedule: { days: ['tue', 'thu'], times: ['morning'], recurring: true },
      locations: [place('spruce_hill', 'Church hall', 0.002, -0.003)],
      cost: free,
      commitment: 'weekly',
      group_size: 'small',
      access: { wheelchair: 'yes' },
      requirements: { kids_ok: true },
      first_step: { how: 'Come to a Tuesday session with your little one', drop_in: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'stroller-walking-group',
      name: 'Stroller Walking Group',
      kind: 'club',
      categories: ['running-cycling-fitness', 'kids-youth-mentoring'],
      interests: ['walking_group'],
      motives: ['social', 'protective'],
      formats: ['side_by_side', 'conversation'],
      roles: ['hands_on'],
      crowd: ['families'],
      audience: { open_to: 'public' },
      schedule: { days: ['mon', 'wed', 'sat'], times: ['morning'], recurring: true },
      locations: [place('manayunk', 'Towpath', 0.003, -0.006)],
      cost: free,
      commitment: 'drop_in',
      requirements: { kids_ok: true },
      first_step: { how: 'Meet at the towpath bench with your stroller', drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'tai-chi-in-the-park',
      name: 'Tai Chi in the Park',
      kind: 'program',
      categories: ['health-wellness'],
      interests: ['tai_chi_qigong'],
      motives: ['protective', 'enhancement'],
      formats: ['learn_skill', 'side_by_side'],
      roles: ['hands_on'],
      crowd: ['seniors', 'all_adults'],
      audience: { open_to: 'public' },
      schedule: { days: ['sat'], times: ['morning'], recurring: true },
      locations: [place('spruce_hill', 'Park lawn', -0.004, -0.004)],
      cost: free,
      commitment: 'drop_in',
      access: { wheelchair: 'yes' },
      first_step: { how: 'Join the back row and copy the teacher', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'community-theater-company',
      name: 'Neighborhood Community Theater',
      kind: 'club',
      categories: ['theater-dance-performance'],
      interests: ['community_theater'],
      motives: ['enhancement', 'social'],
      formats: ['perform_make_together'],
      roles: ['create'],
      crowd: ['all_adults'],
      audience: { open_to: 'public' },
      schedule: { days: ['tue', 'thu'], times: ['evening'], recurring: true },
      locations: [place('manayunk', 'Theater', -0.002, 0.004)],
      cost: low,
      commitment: 'seasonal',
      group_size: 'medium',
      first_step: { how: 'Come to open auditions or sign up for crew', newcomer_friendliness: 3 },
    }),
    g({
      id: 'stage-crew-volunteers',
      name: 'Stage Crew Volunteers',
      kind: 'club',
      categories: ['theater-dance-performance'],
      interests: ['stage_crew'],
      motives: ['understanding', 'social'],
      formats: ['behind_the_scenes'],
      roles: ['hands_on', 'organize'],
      crowd: ['all_adults'],
      audience: { open_to: 'public' },
      locations: [place('manayunk', 'Theater', -0.002, 0.005)],
      cost: free,
      commitment: 'one_off',
      first_step: { how: 'Email the stage manager to join a build day', sign_up_needed: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'mural-arts-volunteers',
      name: 'Mural Arts Volunteer Days',
      kind: 'nonprofit',
      categories: ['arts-crafts'],
      interests: ['mural_public_art'],
      motives: ['values', 'enhancement'],
      formats: ['side_by_side', 'one_off_event'],
      roles: ['create', 'hands_on'],
      crowd: ['all_ages'],
      bridging: true,
      audience: { open_to: 'public' },
      schedule: { days: ['sat'], times: ['daytime'], recurring: false },
      locations: [place('point_breeze', 'Wall', 0.004, -0.003)],
      cost: free,
      commitment: 'one_off',
      first_step: { how: 'Sign up for a paint day', drop_in: false, sign_up_needed: true, newcomer_friendliness: 5 },
      research_tier: 2,
    }),
    g({
      id: 'pottery-open-night',
      name: 'Pottery Studio Open Night',
      kind: 'club',
      categories: ['arts-crafts'],
      interests: ['pottery_ceramics', 'craft_circle'],
      motives: ['enhancement', 'protective', 'social'],
      formats: ['learn_skill', 'side_by_side'],
      roles: ['create', 'hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'public' },
      schedule: { days: ['thu'], times: ['evening'], recurring: true },
      locations: [place('fishtown', 'Studio', 0.004, -0.002)],
      cost: paid,
      commitment: 'weekly',
      group_size: 'small',
      first_step: { how: 'Book an intro class', sign_up_needed: true, newcomer_friendliness: 4 },
    }),

    // ------------------------------------------------------------ the outdoors cluster: stretch candidates (6)
    g({
      id: 'philly-hiking-club',
      name: 'Philly Hiking Club',
      kind: 'club',
      categories: ['outdoors-adventure'],
      interests: ['hiking'],
      motives: ['social', 'protective'],
      formats: ['side_by_side'],
      roles: ['hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['sat'], times: ['morning'], recurring: true },
      locations: [place('mount_airy_east', 'Trailhead', 0.004, 0.004)],
      cost: free,
      commitment: 'weekly',
      group_size: 'medium',
      first_step: { how: 'Join a Saturday hike and ask for the beginner pace', drop_in: true, newcomer_friendliness: 4 },
    }),
    g({
      id: 'philadelphia-grotto',
      name: 'Philadelphia Grotto',
      kind: 'club',
      categories: ['outdoors-adventure'],
      interests: ['caving', 'hiking'],
      motives: ['understanding', 'social'],
      formats: ['learn_skill', 'side_by_side'],
      roles: ['hands_on', 'figure_out'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['thu', 'sat', 'sun'], times: ['evening', 'daytime'], recurring: true },
      locations: [place('rittenhouse', 'Monthly meeting', 0.002, -0.001)],
      cost: low,
      commitment: 'monthly',
      group_size: 'small',
      access: { wheelchair: 'no' },
      first_step: { how: 'Come to a monthly meeting before signing up for a trip', drop_in: true, newcomer_friendliness: 4 },
      research_tier: 2,
    }),
    g({
      id: 'birding-walk-leaders',
      name: 'Beginner Bird Walk Leaders',
      kind: 'club',
      categories: ['outdoors-adventure'],
      interests: ['birding'],
      motives: ['values', 'understanding'],
      formats: [],
      roles: ['help_teach'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['sun'], times: ['morning'], recurring: true },
      locations: [place('mount_airy_east', 'Nature center', 0.006, 0.0)],
      cost: free,
      commitment: 'monthly',
      first_step: { how: 'Walk along first, then ask to lead a short loop', newcomer_friendliness: 4 },
    }),
    g({
      id: 'intergenerational-hiking-meetup',
      name: 'All Ages Hiking Meetup',
      kind: 'network',
      categories: ['outdoors-adventure'],
      interests: ['hiking'],
      motives: ['social'],
      formats: ['side_by_side'],
      roles: ['hands_on'],
      crowd: ['all_ages', 'families', 'seniors'],
      bridging: true,
      audience: { open_to: 'public' },
      schedule: { days: ['sun'], times: ['morning'], recurring: true },
      locations: [place('mount_airy_east', 'Trailhead', -0.002, 0.006)],
      cost: free,
      commitment: 'monthly',
      first_step: { how: 'Meet at the trailhead sign', drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'grotto-trip-leaders',
      name: 'Grotto Trip Leader Program',
      kind: 'club',
      categories: ['outdoors-adventure'],
      interests: ['caving'],
      motives: ['values', 'enhancement'],
      formats: ['learn_skill', 'lead_organize'],
      roles: ['lead', 'hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 18 },
      schedule: { days: ['sat'], times: ['daytime'], recurring: true },
      locations: [place('rittenhouse', 'Training meeting', 0.003, -0.002)],
      cost: low,
      commitment: 'ongoing_role',
      first_step: { how: 'Ask the trip coordinator about shadowing a leader', sign_up_needed: true, newcomer_friendliness: 3 },
    }),
    g({
      id: 'regional-cave-rescue',
      name: 'Regional Cave Rescue Team',
      kind: 'team',
      categories: ['outdoors-adventure', 'emergency-disaster'],
      interests: ['caving', 'search_rescue'],
      motives: ['values'],
      formats: ['team_play', 'learn_skill'],
      roles: ['hands_on', 'lead'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', min_age: 21 },
      locations: [{ label: 'Training sites', in_city: false, lat: 40.6, lng: -76.2 }],
      cost: free,
      commitment: 'ongoing_role',
      requirements: { background_check: true },
      first_step: { newcomer_friendliness: 2 },
    }),

    // ------------------------------------------------------------ rules: support, members only, invitation (4)
    g({
      id: 'grief-support-circle',
      name: 'Grief Support Circle',
      kind: 'support_group',
      categories: ['support-recovery'],
      interests: ['grief_support'],
      motives: ['protective', 'social'],
      formats: ['conversation'],
      roles: ['help_teach'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', support_group: true },
      schedule: { days: ['mon'], times: ['evening'], recurring: true },
      locations: [place('rittenhouse', 'Church hall', 0.0, -0.004)],
      cost: free,
      commitment: 'weekly',
      first_step: { drop_in: true, newcomer_friendliness: 5 },
    }),
    g({
      id: 'recovery-meeting-south',
      name: 'Recovery Meeting South',
      kind: 'support_group',
      categories: ['support-recovery'],
      interests: ['addiction_recovery'],
      motives: ['protective'],
      formats: ['conversation'],
      roles: ['help_teach'],
      crowd: ['all_adults'],
      audience: { open_to: 'public', support_group: true },
      locations: [place('point_breeze', 'Meeting room', -0.002, 0.002)],
      cost: free,
      commitment: 'weekly',
    }),
    g({
      id: 'riverside-boat-club',
      name: 'Riverside Boat Club',
      kind: 'club',
      categories: ['water-rowing'],
      interests: ['rowing'],
      motives: ['social'],
      formats: ['team_play'],
      roles: ['hands_on'],
      crowd: ['all_adults'],
      audience: { open_to: 'members' },
      locations: [place('manayunk', 'Boathouse', 0.003, 0.0)],
      cost: paid,
      commitment: 'weekly',
    }),
    g({
      id: 'supper-club-by-invitation',
      name: 'Supper Club by Invitation',
      kind: 'club',
      categories: ['food-drink'],
      interests: ['foodie_meetups'],
      motives: ['social'],
      formats: ['conversation'],
      roles: ['organize'],
      crowd: ['professionals'],
      audience: { open_to: 'invite' },
      locations: [place('rittenhouse', 'Private homes', 0.004, 0.001)],
      cost: paid,
      commitment: 'monthly',
    }),
  ];
}
